"""
SentinelAI - Windows Event Log Anti-Tampering & Sequence Verifier
"""

from dataclasses import dataclass
from typing import Dict, List, Any

@dataclass
class EVTXTamperIndicator:
    log_channel: str
    event_id: int
    anomaly_type: str
    threat_rating: str

EVTX_TAMPER_PATTERNS: List[EVTXTamperIndicator] = [
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #1", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #2", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #3", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #4", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #5", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #6", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #7", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #8", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #9", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #10", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #11", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #12", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #13", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #14", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #15", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #16", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #17", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #18", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #19", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #20", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #21", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #22", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #23", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #24", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #25", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #26", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #27", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #28", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #29", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #30", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #31", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #32", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #33", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #34", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #35", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #36", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #37", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #38", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #39", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #40", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #41", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #42", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #43", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #44", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #45", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #46", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #47", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #48", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #49", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #50", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #51", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #52", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #53", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #54", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #55", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #56", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #57", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #58", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #59", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #60", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #61", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #62", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #63", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #64", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #65", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #66", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #67", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #68", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #69", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #70", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #71", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #72", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #73", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #74", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #75", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #76", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #77", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #78", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #79", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #80", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #81", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #82", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #83", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #84", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #85", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #86", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #87", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #88", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #89", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #90", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #91", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #92", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #93", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #94", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #95", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #96", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #97", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #98", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #99", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #100", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #101", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #102", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #103", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #104", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #105", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #106", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #107", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #108", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #109", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #110", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #111", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #112", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #113", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #114", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #115", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #116", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #117", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #118", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #119", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #120", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #121", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #122", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #123", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #124", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #125", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #126", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #127", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #128", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #129", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #130", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #131", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #132", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #133", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #134", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #135", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #136", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #137", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #138", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #139", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #140", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #141", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #142", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #143", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #144", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #145", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #146", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #147", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #148", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #149", threat_rating="CRITICAL"),
    EVTXTamperIndicator(log_channel="Security.evtx", event_id=1102, anomaly_type="Log Clear Anomaly #150", threat_rating="CRITICAL"),
]
def get_evtx_tamper_rules() -> List[EVTXTamperIndicator]: return EVTX_TAMPER_PATTERNS
